export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const SET_ITEMS = 'SET_ITEMS';
export const FETCH_ITEMS_FAILED = 'FETCH_ITEMSS_FAILED';

export const PURCHASE_BREAKFAST_START = 'PURCHASE_BREAKFAST_START';
export const PURCHASE_BREAKFAST_SUCCESS = 'PURCHASE_BREAKFAST_SUCCESS';
export const PURCHASE_BREAKFAST_FAIL = 'PURCHASE_BREAKFAST_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';