export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const SET_ITEMS = 'SET_ITEMS';
export const FETCH_ITEMS_FAILED = 'FETCH_ITEMSS_FAILED';

export const PURCHASE_BREAKFAST_START = 'PURCHASE_BREAKFAST_START';
export const PURCHASE_BREAKFAST_SUCCESS = 'PURCHASE_BREAKFAST_SUCCESS';
export const PURCHASE_BREAKFAST_FAIL = 'PURCHASE_BREAKFAST_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';